Update senv

diff --git a/bin/senv b/bin/senv
--- a/bin/senv
+++ b/bin/senv
@@ -1,68 +1,84 @@
-#!/usr/bin/env ruby
+#!/usr/bin/env bash
 
-require 'base64'
-require 'openssl'
-require 'optparse'
-require 'shellwords'
+usage() {
+  echo "usage: senv [-e | -d] <file>"
+}
 
-options = {}
-optparse = OptionParser.new do |opts|
-  opts.banner = "Usage: senv [-e | -d] <file>"
+unset encrypt decrypt file
 
-  opts.on("-e", "--encrypt", "Encrypt file or input") do
-    options[:encrypt] = true
-    options[:file] = ".env"
-  end
-  opts.on("-d", "--decrypt", "Decrypt file or input") do
-    options[:decrypt] = true
-    options[:file] = ".senv"
-  end
-  opts.on("-h", "--help", "Show help") do
-    puts opts
-    exit
-  end
-end
+if [ "$1" = "-e" ] || [ "$1" = "--encrypt" ]; then
+  encrypt=1
+  [ -t 0 ] && file=".env"
+  shift
+fi
 
-begin
-  optparse.parse!
-rescue OptionParser::InvalidOption
-  abort optparse.to_s
-end
+if [ "$1" = "-d" ] || [ "$1" = "--decrypt" ]; then
+  decrypt=1
+  [ -t 0 ] && file=".senv"
+  shift
+fi
 
+if [ "${1:0:1}" = "-" ]; then
+  echo "senv: invalid option: $1" >&2
+  usage >&2
+  exit 1
+fi
 
-ENV['SENV_KEY'] ||= `ssh-add -l`.lines.first.split(" ")[2]
+if [ -n "$1" ]; then
+  file="$1"
+fi
 
-if File.exist?(ENV['SENV_KEY'])
-  result = `#{Shellwords.join(['security', 'find-generic-password', '-ga', ENV['SENV_KEY']])} 2>&1`
-  if $?.success?
-    password = result[/^password: "(.*)"$/, 1]
-  end
-  key = OpenSSL::PKey::RSA.new(File.read(ENV['SENV_KEY']), password)
+if [ ! -t 0 ] && [ -z "$file" ]; then
+  file="/dev/stdin"
+elif [ -z "$file" ]; then
+  usage >&2
+  exit 1
+elif [ ! -e "$file" ]; then
+  echo "senv: $file: No such file or directory" >&2
+  exit 1
+elif [ ! -f "$file" ]; then
+  echo "senv: $file: Is a directory" >&2
+  exit 1
+fi
+
+if [ -z "$SENV_KEY" ]; then
+  SENV_KEY=$(ssh-add -l | head -n1 | awk -F ' ' '{print $3}')
+fi
+
+if [ ! -e "$SENV_KEY" ]; then
+  echo "senv: $SENV_KEY: No such file or directory" >&2
+  exit 1
+fi
+
+findpass() {
+  security find-generic-password -ga $SENV_KEY 2>&1 1>/dev/null |
+    head -n1 |
+    cut -d ' ' -f 2 |
+    sed "s/\"//g"
+}
+
+unset passin
+if [ -n "$encrypt" ] || [ -n "$decrypt" ]; then
+  PASS=$(findpass)
+  if [ "$?" -eq 0 ] && [ -n "$PASS" ]; then
+    export PASS
+    passin="-passin env:PASS"
+  fi
+fi
+
+if [ -n "$encrypt" ]; then
+  while read line; do
+    result=$(echo "$line" | openssl rsautl -encrypt -inkey "$SENV_KEY" $passin | openssl base64 -A)
+    echo $result
+  done < $file
+  exit 0
+elif [ -n "$decrypt" ]; then
+  while read line; do
+    result=$(echo "$line" | openssl base64 -A -d | openssl rsautl -decrypt -inkey "$SENV_KEY" $passin 2>/dev/null)
+    echo $result
+  done < $file
+  exit 0
 else
-  abort "SENV_KEY=#{ENV['SENV_KEY']} does not exist"
-end
-
-if STDIN.tty? && ARGF.path == "-"
-  if options[:file] && File.exist?(options[:file])
-    input = File.open(options[:file], 'r')
-  else
-    abort optparse.to_s
-  end
-else
-  input = ARGF
-end
-
-if options[:encrypt]
-  input.each_line do |line|
-    puts Base64.strict_encode64(key.public_encrypt(line.chomp))
-  end
-elsif options[:decrypt]
-  input.each_line do |line|
-    begin
-      puts key.private_decrypt(Base64.strict_decode64(line.chomp))
-    rescue Exception
-    end
-  end
-else
-  abort optparse.to_s
-end
+  usage >&2
+  exit 1
+fi
